### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by myaserkhan** [myaserkhan/JavaScript-API-based-webapp#21]
Hello there, 

This is the link to our project: https://github.com/myaserkhan/JavaScript-API-based-webapp/projects/1

We are group of two coding panthers:

> @myaserkhan 
> @nunegabriel

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @myaserkhan and @nunegabriel,

Good job so far!
✔️ Kanban columns are well copied
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Since there are only two members in this group kindly remove all Student C tasks.

- [ ] Kindly assign your tasks as well

  ![andre-assigned](https://user-images.githubusercontent.com/36542986/197534686-b5c483ad-6127-4a30-9359-18c9b8773cb6.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by youmari** [comment]
Hi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ PRO issue

## Required Changes ♻️

- [ ]  it would be better if you assign both of you to cards equally as required by the previous reviewer in order to match the requirements
- Yours 
<img width="329" alt="Screen Shot 2022-10-24 at 14 23 39" src="https://user-images.githubusercontent.com/61790587/197536393-3ebb11c5-ed06-4ef8-9f7a-3335e6294e1e.png">
- it should be like this 

![](https://user-images.githubusercontent.com/36542986/197534686-b5c483ad-6127-4a30-9359-18c9b8773cb6.jpg)
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GiuseppeTG** [comment]
Hi @myaserkhan @nunegabriel  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥇 : 
Congratulations! 🎉 

![Alt Text](https://media3.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

## Highlights
✅ Good job with the changes required!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
